### ISSUE TITLE
Text exceeds standard Obsidian margins

### ISSUE THREAD

**Issue by carterchannui** [SamZhang02/obsidian-latex-algorithms#1]
Is there a way to have the algorithm code block wrap the LaTeX?

![Screenshot 2023-03-13 at 9 04 40 PM](https://user-images.githubusercontent.com/26908609/224890481-8a6f4890-46c7-430e-8af3-54b8f97a24e5.png)

**Comment by SamZhang02** [comment]
I believe this is a MathJax thing: 
https://docs.mathjax.org/en/latest/output/linebreaks.html
> Automatic line breaking has not yet been implemented in MathJax version 3, but is high on our list for inclusion in a future release.

MathJax isn't great and lack features, which is why I made this plugin to begin with; but I certainly did not expect it to not even have any kind of automatic line breaking.

There might be some workaround by manipulating the CSS, but I have not looked into it yet. I will let you know if I do find one.

**Comment by SamZhang02** [comment]
Closing since this is not a plugin or Obsidian issue
